src/main/groovy/org/asciidoctor/gradle/AsciidoctorPlugin.groovy
src/test/groovy/org/asciidoctor/gradle/AsciidoctorPluginSpec.groovy

improve dependency version handling as seen in https://github.com/melix/jmh-gradle-plugin/pull/27
done during Hackergarten Basel :-)

change dependency version handling to make resolving deps more reliable

---

HACKING.adoc

This is a start of a document that was triggered by the discussion in #151.

Added a HACKING.adoc document 

---

README.adoc

Use the correct AsciiDoc attribute in URL (project-name instead of project-full-path).

Fix Bintray download badge

---

README.adoc

- hide status except when viewed on GitHub
- show icons when viewed GitHub
- enable toc when viewed on GitHub or through browser preview
- hide contributing section except when viewed on GitHub
- use incremental subs to enable attributes in source listings
- fix capitalization of some section titles
- move compatibility section to appendix
- rename section titles under custom extensions section for clarity

update README to incorporate into asciidoctor.org

---

README.adoc

Add example custom source and output config; tips per issue #188

---

README.adoc

- add link to examples project
- clarify Usage introduction
- mark recommended file extension
- minor rewording

add link to examples project

---

.gitlab-ci.yml
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy
gradle/compatibility-tests.gradle

As per a recommendation from @bamboo in gradle/kotlin-dsl#1353.

Prevent AsciidoctorJExtension from being ExtensionAware (#284,#298)

---

README.adoc

some options are not rendered well due by a typo

typo at highlightJsThemeLocation

---

README.adoc

Correct minor typos

---

README.adoc
asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AsciidoctorModuleDefinition.java
asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AsciidoctorUtils.groovy
asciidoctor-gradle-jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorJEpubPlugin.groovy
asciidoctor-gradle-jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorJRevealJSTask.groovy
asciidoctor-gradle-jvm/src/gradleTest/complex-jvm-setup/build.gradle
asciidoctor-gradle-jvm/src/gradleTest/complex-jvm-setup/build.gradle.kts
asciidoctor-gradle-jvm/src/gradleTest/extension-in-subproject/docs-using-configuration/build.gradle
asciidoctor-gradle-jvm/src/gradleTest/extension-in-subproject/docs-using-project-direct/build.gradle
asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/ExtensionsFunctionalSpec.groovy
asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/RequiresFunctionalSpec.groovy
asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/ResourcesFunctionalSpec.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/compat/AsciidoctorCompatibilityTask.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/internal/ExecutorConfiguration.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePlugin.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJModules.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJPdfPlugin.groovy
asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/remote/ExecutorBase.groovy
asciidoctor-gradle-jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePluginSpec.groovy
gradle.properties
gradle/compatibility-tests.gradle

- #347 Deprecate *[eE]xtensions in favour of *[dD]Extensions
- #348 Configure component and converter versions in a modules block
- #349 Update to grolifant 0.12.1

Deprecating certain DSL elements and introducing new ones

---

README.adoc

small typo but prone to error if copy&paste

small typo

---

asciidoctor-gradle-jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorJRevealJSTask.groovy
asciidoctor-gradle-jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSBasePlugin.groovy
asciidoctor-gradle-jvm-slides/src/test/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSPluginSpec.groovy
asciidoctor-gradle-jvm-slides/src/test/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSTaskSpec.groovy

Only add Reveal GEM to asciidoctorj extension to task extension

---

asciidoctor-gradle-jvm-gems/src/gradleTest/external-gems/build.gradle

Reverts asciidoctor/asciidoctor-gradle-plugin#397

Revert "Fix version of bibtex-ruby to 4.4.7 for test purposes"

---

asciidoctor-gradle-jvm-epub/src/intTest/groovy/org/asciidoctor/gradle/jvm/epub/LinkedChaptersFunctionalSpec.groovy
asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/chapter1.adoc
asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/chapter2.adoc
asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/epub3.adoc

EPUB linked chapters test

---

docs/src/docs/asciidoc/index.adoc

Fixes missing documentation on custom extensions.

Fix syntax error in include on custom extensions

---

docs/src/docs/asciidoc/parts/asciidoctorj-pdf-plugin.adoc

The repo was moved to a dedicated personal account

Update github org

---

base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
base/src/test/groovy/org/asciidoctor/gradle/base/BaseTaskPatternSpec.groovy

Fix bug in AbstractAsciidoctorBaseTask#sources(java.lang.String...)

---

docs/src/docs/asciidoc/parts/common-task-configuration.adoc

no problem (to rebase to 3.x) @ysb33r !

fix some typos in the docs

---

docs/src/docs/asciidoc/parts/asciidoctorj-revealjs-plugin.adoc
jvm-slides/src/gradleTest/basic-slides/build.gradle
jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/RevealJSOptions.groovy
jvm-slides/src/test/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSTaskSpec.groovy
jvm-slides/src/test/groovy/org/asciidoctor/gradle/jvm/slides/RevealJSOptionsSpec.groovy

resolves #500 slideNumber is a string

---

jvm/src/main/groovy/org/asciidoctor/gradle/internal/ExecutorConfiguration.groovy
jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy
jvm/src/remoteTest/groovy/org/asciidoctor/gradle/remote/internal/RemoteSpecification.groovy
jvm/src/test/groovy/org/asciidoctor/gradle/internal/ExecutorConfigurationSpec.groovy
jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskSpec.groovy

resolves #509 requires must guarantee order

---

jvm-epub/src/intTest/groovy/org/asciidoctor/gradle/jvm/epub/LinkedChaptersFunctionalSpec.groovy
module-versions.properties

Bump asciidoctor-epub3 to 1.5.0-alpha.13

---

docs/src/docs/asciidoc/parts/common-task-configuration.adoc

Improved docs to avoid #556.
Fixes #568

Improved docs to avoid #556

---

README.adoc

fix broken link to 2.0 branch, which is now maitenance

fix README - update link to 2.0 branch

---

jvm-pdf/src/intTest/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTaskFunctionalSpec.groovy
jvm-pdf/src/main/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTask.groovy
jvm-pdf/src/main/groovy/org/asciidoctor/gradle/jvm/pdf/PdfFontDirException.groovy

This merge request fixes https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/561

Fix file path parsing

---

docs/src/docs/asciidoc/parts/asciidoctorj-pdf-plugin.adoc

Fix pdfThemes local theme example

---

CONTRIBUTING.adoc
README.adoc
build.gradle

This is the initial version for a CONTRIBUTING file. 
I put in what I could think of but I also know that it may not be enough. 
Hope it can start a discussion on what to include in the file at least

Add contributing readme

---

jvm-pdf/src/intTest/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTaskFunctionalSpec.groovy
jvm-pdf/src/main/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTask.groovy

#579 Fixes Gradle deprecation warning in Gradle 6.x

---

module-versions.properties

Update the version of the groovydsl to one that is available from Maven Central.

---

docs/src/docs/asciidoc/parts/common-task-configuration.adoc

Update incorrect default outputDir

---

docs/src/docs/asciidoc/parts/asciidoctorj-compatiblity-plugin.adoc
docs/src/docs/asciidoc/parts/common-task-configuration.adoc

update outputDir default value in doc as defined in #537

537: Documentation shows wrong default outputDir

---

gradle.properties
jvm-epub/build.gradle
jvm-pdf/build.gradle
jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy

When a JRuby version is explicitly named, force to that version.

---

docs/modules/ROOT/pages/asciidoctorj-revealjs-plugin.adoc
docs/modules/ROOT/pages/docinfo.adoc
jvm-slides/src/gradleTest/basic-slides/build.gradle
jvm-slides/src/intTest/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSTaskCachingFunctionalSpec.groovy
jvm-slides/src/intTest/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSTaskFunctionalSpec.groovy
jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorJRevealJSTask.groovy
jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/RevealJSPluginExtension.groovy
module-versions.properties

Adopt and document Reveal.js plugin configuration.

Upgrade reveal.js to version 5.1.0
