- build.gradle
- src/test/groovy/org/asciidoctor/gradle/AsciidoctorTaskInlineExtensionsSpec.groovy
This PR bumps asciidoctorj-groovy-dsl to the last version 1.0.0.Alpha1.
"Highlights" of this release are:
- Dependencies on groovy is bumped to the same version as the gradle plugin. (Required some changes in the DSL base script class)
- Methods inlinemacro, includeprocessor, blockmacro are deprecated now.
Instead the methods inline_macro, include_processor and block_macro should be used in the future.
- A new method docinfo_processor allows to define docinfo processors.
```
extensions {
docinfo_processor {
document -> '<meta name="hello" content="world">'
}
}
```
> Upgrade asciidoctorj-groovy-dsl to 1.0.0.Alpha1

- HACKING.adoc
- README.adoc
- use published version in examples in README.adoc
- show example of using SNAPSHOT version in HACKING.adoc
- fix missing specialcharacters sub on source blocks
> use published version in examples in README.adoc

- src/main/groovy/org/asciidoctor/gradle/AsciidoctorUtils.groovy
- src/test/groovy/org/asciidoctor/gradle/AsciidoctorUtilsSpec.groovy
When trying to perform Asciidoctor conversion on files in root of the
project, i.e. when AsciidoctorUtils.getRelativePath receives exact
target and base directories the build results in failure caused by
StringIndexOutOfBoundsException on line 57. This patch resolves this
corner case and adds tests for other cases.
> AsciidoctorUtils.getRelativePath with same target and base

- README.adoc
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorExtension.groovy
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorPlugin.groovy
- src/test/groovy/org/asciidoctor/gradle/AsciidoctorPluginSpec.groovy
This addresses #174 by adding a `noDefaultRepositories` property to `asciidoctorj` extension block.
> Flexibility to turn jcenter as default repo off

- gradle.properties
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorExtension.groovy
As pointed out in asciidoctor/asciidoctorj-groovy-dsl#14 the current released version of the asciidoctor-gradle-plugin uses old versions of the asciidoctorj-groovy-dsl.
This PR sets the dependency to the current version again.
> Bump asciidoctorj-groovy-dsl to current version 1.0.0.Alpha2

- src/main/groovy/org/asciidoctor/gradle/AsciidoctorProxyCacheKey.groovy
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorProxyImpl.groovy
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorTask.groovy
- src/test/groovy/org/asciidoctor/gradle/AsciidoctorTaskInlineExtensionsSpec.groovy
- src/test/groovy/org/asciidoctor/gradle/AsciidoctorTaskSpec.groovy
This PR changes the AsciidocTask implementation to reuse the asciidoctor
instance to avoid reinstantiating the jruby runtime which is expensive.
Especially when running builds in continous mode with -t reusing the
asciidoctor instance solves two issues:
1. Everytime jruby runtime is loaded we see about > 5000 classes
leaking into the classloader
2. As a consequence of 1) the build gets slower and slower over time.
I've attached two profiling screenshots showing the impact of that change to classloader leakage when constantly running asciidoctor task in a gradle continous build (`./gradlew asciidoctor -t`):
Before:
After:
> Make Asciidoc task much faster by reusing JRuby runtime.

- src/intTest/groovy/org/asciidoctor/gradle/AsciidoctorFunctionalSpec.groovy
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorTask.groovy
Previously, the AsciidoctorTask did not consider its classpath to be an input. This meant that a change to task's classpath did not stop it from considering itself to be up-to-date.
This pull request annotates the classpath property with `@InputFiles` so that it's considered when performing up-to-date checks. It's also been annotated with `@Optional` as the property can be `null`.
> Ensure that AsciidoctorTask is not up-to-date when classpath changes

- README.adoc
Hi,
currently it is not so easy to use plug-in with the Gradle Kotlin DSL. Although it is not officially released, a lot of people are using it already. At the moment the plug-in does not work nicely with it and it took me a while to get a non-trivial setup working. So I thought some documentation would be helpful for others in the same situation.
I hope I will be able to contribute some code to allow for a more "natural" use by making the workarounds unnecessary. But I cannot promise that, unfortunately.
Anyway, thank you for this great plug-in! I use it on a daily basis and it became invaluable.
Best,
Manuel
> Document how to use the plugin with the Gradle Kotlin DSL

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
This PR updates Grade to 4.7.
Gradle 4.7 is the first gradle version which offically support running on Java 10.
This PR also implicitly updates JaCoCo from 0.8.0 to 0.8.1.
> Allow the project to be compiled on Java 10

- README.adoc
- appveyor.yml
- asciidoctor-gradle-jvm/src/gradleTest/complex-jvm-setup/build.gradle
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/internal/FunctionalSpecification.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/AsciidoctorPdfTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/ExtensionsFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/RequiresFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/internal/AsciidoctorUtils.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/internal/ExecutorConfiguration.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/internal/ExecutorLogLevel.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/remote/AsciidoctorJavaExec.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/remote/ExecutorBase.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/remote/LogSeverityMapper.groovy
- gradle.properties
- gradle/ci.gradle
- gradle/compatibility-tests.gradle
- testfixtures/jvm/src/main/groovy/org/asciidoctor/gradle/testfixtures/jvm/generators/VersionProcessModeGenerator.groovy
Also optimised test approach:
- Do not allow extension tests to take more than 3 min each.
- Use specific JRuby versions for 1.6.x testing.
- Update the test listener for CI to monitor output.
- Add a generator to testfixtures for providing AJ version + process mode
- When running on Appveyor only use JAVA_EXEC.
> Allow Java fork options to be specified (#240)

- asciidoctor-gradle-base/build.gradle
- asciidoctor-gradle-jvm-epub/build.gradle
- asciidoctor-gradle-jvm/build.gradle
- build.gradle
- gradle/asciidoctorj-versions.gradle
- gradle/publishing.gradle
- kindlegen-gradle/build.gradle
Add extension mentohd to make it easier to configure both `gradlePlugins` and `publishPlugins` in one go.
Did not enable Bintray yet, as this is a legacy way of publishing plugins and requires setting of a version attribute. The problem with this situation is that it assumes only one plugin per jar, which is not the case for plugins nowadsys.
> Rework publishing to the Gradle Plugin Portal

- src/main/groovy/org/asciidoctor/gradle/backported/AsciidoctorJavaExec.groovy
I'm not sure if this change was intentional, but with the backport commit, these attribute names were changed. I think this change should be left for 2.0 where it has been documented.
> revert projectdir and rootdir attribute names back to 1.5.x pattern

- gradle.properties
- src/intTest/groovy/org/asciidoctor/gradle/AsciidoctorFunctionalSpec.groovy
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorExtension.groovy
- src/main/groovy/org/asciidoctor/gradle/AsciidoctorTask.groovy
Restore usage of:
- project-version
- project-group
- project-name
Detect usage of all three and print a warning to rather use
- revnumber
- gradle-project-group
- gradle-project-name
All three the latter attributes will also be injected to aid migration
to 2.x releases.
Bump to use asciidoctorj 1.6.1.
> Release 1.5.10

- README.adoc
Correct these typos below:
- `aalows` -> `allows`
- `aand` -> `and`
> Correct typos in README

- README.adoc
In the "Upgrading From Older Versions of Asciidoctor" section, the table is broken because of a wrong `cols` attribute configuration.
> README: Fix old/new attributes table

- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
- Only add revnumber when project.version is non-null.
- Only add gradle-project-group when project.group is non-null.
> Conditionally add revnumber and gradle-project-group (#328,#329)

- README.adoc
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/intTest/projects/normal/src/docs/asciidoc/subdir/sample2.ad
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/remote/ExecutorBase.groovy
Add this attribute to show the relative path of the containing
directory of the current document that is being processed, to
the source root (i.e. `asciidoctor.sourceDir`).
> gradle-relative-srcdir attribute

- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/remote/AsciidoctorJavaExec.groovy
- asciidoctor-gradle-jvm/src/remoteTest/groovy/org/asciidoctor/gradle/remote/internal/RemoteSpecification.groovy
When running in JAVA_EXEC mode with three or more backends, but
no additional GEMs specified, the system failed with
`ArrayIndexOutOfBoundsException`. The reason was that `::` was
passed down to AsciidoctorJ as the GEM path. The solution is
not to add empty GEM paths to the GEM search path.
> Do not add empty GEM paths for multiple backends (#324)

- README.adoc
as asciidoctor exists as keyword you can't use asciidoctor as an identifier for configurations
> can't use asciidoctor as configuration

- README.adoc
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/compat/AsciidoctorCompatibilityPlugin.groovy
The plugin is sometimes displaying this hint line:
```
You are using one or more deprecated Asciidoctor task or plugins. To help with migration run with --warnings=all
```
But when you run `./gradlew asciidoctor --warnings=all`
You get:
```
> Configure project :
You are using one or more deprecated Asciidoctor task or plugins. To help with migration run with --warnings=all
FAILURE: Build failed with an exception.
* What went wrong:
Problem configuring task :asciidoctor from command line.
> Unknown command-line option '--warnings'.
* Try:
Run gradlew help --task :asciidoctor to get task usage details. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org …
```
> Fixing --warning-mode command-line option

- asciidoctor-gradle-jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorJEpubPlugin.groovy
- asciidoctor-gradle-jvm-gems/src/main/groovy/org/asciidoctor/gradle/jvm/gems/AsciidoctorGemSupportPlugin.groovy
- asciidoctor-gradle-jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSBasePlugin.groovy
- asciidoctor-gradle-jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSPlugin.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/compat/AsciidoctorCompatibilityPlugin.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePlugin.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJPdfPlugin.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJPlugin.groovy
- Use fully qualified class name when applying plugin to workaround https://github.com/gradle/gradle/issues/1262
Background:
In the organization I work with, asciidoctor is used in gradle builds via a custom script plugin that is copied to the "gradle" folder of the projects that need asciidoctor. The script plugin is activated by applying the script plugin in the gradle build.
This solution is currently using asciidoctor-gradle-plugin version 1.5.7. When I tried to upgrade the version to the latest plugin version, I noticed that the internal usage of applying plugins doesn't work with script plugins and I wasn't able to upgrade the solution.
> Fix compatibility with script plugins

- README.adoc
- asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- asciidoctor-gradle-jvm-leanpub/src/main/groovy/org/asciidoctor/gradle/jvm/leanpub/DropboxCopyTask.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/MultiLanguageFunctionalSpec.groovy
- gradle.properties
`getSourceFileTree` and `getSecondarySourceFileTree` now reports all of the source sets when
multiple languages are specified. This fix distinguishes between classic behaviour and
multi-language behaviour and will either return a single source set of a combination of source sets.
Credits to @ixchelruiz for helping to diagnose this problem at Hack.Commit.Push 2019.
> Source trees should report all language source sets (#401)

- asciidoctor-gradle-jvm-gems/src/gradleTest/external-gems/build.gradle
Tests are failing due to a bibtex-ruby update on June 12. In order to prevent this from affecting anyone working on 2.x this merge should go straight to master.
This locks the version of transitive dependency bibtex-ruby version to 4.4.7
> Fix version of bibtex-ruby to 4.4.7 for test purposes

- README.adoc
- asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AbstractImplementationEngineExtension.groovy
- asciidoctor-gradle-base/src/test/groovy/org/asciidoctor/gradle/base/AbstractImplementationEngineExtensionSpec.groovy
- asciidoctor-gradle-base/src/test/resources/META-INF/asciidoctor.gradle/org.asciidoctor.gradle.base.test.properties
- asciidoctor-gradle-js/src/main/groovy/org/asciidoctor/gradle/js/nodejs/AbstractAsciidoctorNodeJSTask.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
When multiple languages have been specified `lang@` will be injected with a value
as specified for the specific language.
It is also now possible to specify additional attributes that will only be injected when a specific language is being converted.
> Inject `lang` attribute for multiple language source sets (#411)

- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePlugin.groovy
Add rule that follows <asciidocTaskName>Dependencies pattern.
Old asciidoctorjDependencies task will now print a deprecation warning.
> Asciidoctor dependency reports on a per-task basis (2.x)

- asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AsciidoctorBasePlugin.groovy
- asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/internal/ConfigurationUtils.groovy
- asciidoctor-gradle-base/src/test/groovy/org/asciidoctor/gradle/base/AsciidoctorBasePluginSpec.groovy
- asciidoctor-gradle-js/src/main/groovy/org/asciidoctor/gradle/js/nodejs/AbstractAsciidoctorNodeJSTask.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePlugin.groovy
- asciidoctor-gradle-jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePluginSpec.groovy
Apply rule such that if task AsciidoctorAbc exists then AsciidoctorAbcDependencies
will be a report task of all of the appropriate dependencies.
For AsciidoctorJ the runtime dependencies and additional GEMs are reported.
For AsciidoctorJS the Node.JS modules are reported.
> Report dependencies for any Asciidoctor task (#393)

- asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- asciidoctor-gradle-jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorEpubTask.groovy
Exclude secondary source elements by matching rather than subtraction (#410)
This is a very subtle issue. When two Filtree instances are subtracted from each other
in order to eliminate a set of files, the base directory of the tree is lost. If this is
in a CopySpec the relative paths will thus also be lost. The solution is to use a matcher
of type PatternFilterable and then to exclude by FileTreeElement.
When using
> Exclude secondary source elements by matching rather than subtraction

- README.adoc
- docs/src/docs/asciidoc/parts/compatibility.adoc
This PR removes outdated Spring REST Docs incompatibility notes as it does seem to be compatibile now.
See https://github.com/spring-projects/spring-restdocs/issues/581 and https://github.com/spring-projects/spring-restdocs/issues/630
> Remove outdated Spring REST Docs incompatibility notes

- docs/src/docs/asciidoc/parts/common-task-configuration.adoc
This PR escapes `{includedir}` in doc as it'll be replaced with the value of the `{includedir}` attribute.
> Polish Task Configuration section in doc

- docs/src/docs/asciidoc/index.adoc
This PR fixes `include` directive for `asciidoctorj-custom-extensions.adoc`.
> Fix include directive for asciidoctorj-custom-extensions.adoc

- docs/src/docs/asciidoc/parts/common-task-configuration.adoc
escape include dir macro as currently to renders with the travis include dir value
also, set file name for snuppet (as it currently renders "null)
> escape includedir macro

- asciidoctor-gradle-jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorEpubTask.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorPdfTask.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTask.groovy
This is a followup to https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/215.
Since Gradle 5.0 only adding `@CacheableTask` is needed.
This should not break compatibility with earlier Gradle versions:
- Gradle versions prior to the introduction of the `@CacheableTask` annotation (before 3.0) will just not see the annotation,
- Gradle versions prior 5.0 will emit a deprecation warning about an `@OutputDirectories` property being a `Set<>` and disable caching, but otherwise succeed,
- Gradle versions 5.0 and later will cache the output as intended.
> Make tasks cacheable

- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
Gradle 6.0+ will print this message when warnings are enabled.
```
> Task :asciidoctor
Property 'baseDirConfigured' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```
Using `@Internal` annotation dismiss the public property from up-to-date checks, and as such prevent warnings.
> Avoid deprecation warning for `baseDirConfigured` with Gradle 6.0

- docs/src/docs/asciidoc/parts/asciidoctorj-base-plugin.adoc
Documents the actual behavior of AsciidoctorJExtension which uses
the `gradle-` prefix.
> Add missing gradle- prefix to automatically added attributes

- asciidoctor-gradle-jvm-epub/src/intTest/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorEpubTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm-epub/src/intTest/groovy/org/asciidoctor/gradle/jvm/epub/internal/FunctionalSpecification.groovy
- asciidoctor-gradle-jvm-gems/src/intTest/groovy/org/asciidoctor/gradle/jvm/gems/AsciidoctorGemPrepareTaskCachingFunctionalSpec.groovy
- asciidoctor-gradle-jvm-gems/src/intTest/groovy/org/asciidoctor/gradle/jvm/gems/internal/FunctionalSpecification.groovy
- asciidoctor-gradle-jvm-slides/src/intTest/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm-slides/src/intTest/groovy/org/asciidoctor/gradle/jvm/slides/internal/FunctionalSpecification.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/internal/FunctionalSpecification.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/AsciidoctorPdfTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskFunctionalSpec.groovy
- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorPdfTask.groovy
- testfixtures/jvm/src/main/groovy/org/asciidoctor/gradle/testfixtures/jvm/CachingTest.groovy
This fixes #474 and adds some tests to check for deprecated usages for each of the tasks.
Note that #474 suggests using `@Input` here but the theme name is only used locate the theme directory which is already an input to the task.  The theme name itself is not important to the incrementality or cacheability of the task, hence `@Internal` is more appropriate.
Note also that the `AsciidoctorGemPrepare` task extends from the `JRubyPrepare` task from the jruby plugin which has an un-annotated `dependencies` property which causes a deprecation warning.  This will need to be fixed in the upstream plugin.
cc @facewindu
> Fix deprecation issue when using Gradle 6

- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- base/src/main/groovy/org/asciidoctor/gradle/base/basedir/BaseDirIsNull.groovy
- docs/src/docs/asciidoc/parts/common-task-configuration.adoc
- jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/RelativeIncludeFunctionalSpec.groovy
- jvm/src/intTest/projects/relative-include/src/docs/asciidoc/nested/_nested-include.adoc
- jvm/src/intTest/projects/relative-include/src/docs/asciidoc/nested/sample.adoc
- jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskSpec.groovy
- solves issue reported in #454 . `baseDirFollowsSourceDir()` doesn't work when there are sub directories in the source directory and the expectation is that include resolves the included file relatively from the source file location.
Works based on this behavior:
- `Options.BASEDIR` gets set to `file.parentFile` in `org.asciidoctor.gradle.remote.ExecutorBase#normalisedOptionsFor`
when a null `baseDir` gets passed to the method: https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/952e76434adbf1806192c97e0e5db4a9a5f4eff3/jvm/src/main/groovy/org/asciidoctor/gradle/remote/ExecutorBase.groovy#L82
Asciidoctor's manual includes this explanation:
https://asciidoctor.org/docs/user-manual/#include-resolution
> The base directory defaults to the directory of the main document and can be …
> Add baseDirFollowsSourceFile() to restore support for include directive with relative path

- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- base/src/main/groovy/org/asciidoctor/gradle/base/AsciidoctorUtils.groovy
- js/src/main/groovy/org/asciidoctor/gradle/js/nodejs/AsciidoctorTask.groovy
- jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorEpubTask.groovy
- jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorJEpubPlugin.groovy
- jvm-leanpub/src/main/groovy/org/asciidoctor/gradle/jvm/leanpub/AsciidoctorJLeanpubPlugin.groovy
- jvm-pdf/src/intTest/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTaskFunctionalSpec.groovy
- jvm-pdf/src/main/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorJPdfPlugin.groovy
- jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSPlugin.groovy
- jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTask.groovy
Fixes https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/478.
This changes `AbstractAsciidoctorBaseTask` to use property objects for `sourceDir` and `outputDir` and use conventions to set up the default values (avoiding the ordering problem in the issue above).  Note that there is some byzantine logic around setting up the conventions due to all the flux with the Provider API between versions 4, 5, and 6.  This has mostly stabilized in 6.x, so as support is dropped for older Gradle versions, this logic should get simpler, too.
Note the removal of the default value in the constructor for `AsciidoctorEpubTask`.  As near as I can tell, that was virtually always being overwritten by the default value being set in `AsciidoctorJEpubPlugin`, so I removed the one in the task …
> Use property objects for sourceDir and outputDir

- asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
- asciidoctor-gradle-jvm/src/test/groovy/org/asciidoctor/gradle/jvm/BaseTaskPatternSpec.groovy
- method was a no-op
- backport of #495 for development-3.x branch to development-2.0 branch
> Fix bug in AbstractAsciidoctorTask#sources(java.lang.String...)

- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- base/src/test/groovy/org/asciidoctor/gradle/base/BaseTaskPatternSpec.groovy
- there is already "clearSecondarySources()" so adding this method would
make it symmetrical
> Add "clearSources()" method to base task

- jvm-slides/src/intTest/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorSlidesAndConvertPluginsCoexistFunctionalSpec.groovy
- jvm-slides/src/intTest/projects/coexist/src/docs/asciidoc/sample.asciidoc
- jvm-slides/src/intTest/projects/coexist/src/docs/slides/revealjs.adoc
- jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorJRevealJSTask.groovy
- fixes #464, #388
- fixes error "no such file to load -- asciidoctor-revealjs"
- this error happened if asciidoctorGemsPrepare task hadn't been run
before running asciidoctor task
- AsciidoctorJRevealJSTask registered the ruby module requirement of
asciidoctor-revealjs to the project level AsciidoctorJExtension.
Issue is fixed by using the task level AsciidoctorJExtension.
> Allow slides and convert plugins to co-exist

- docs/src/docs/asciidoc/appendix/tips-and-tricks.adoc
- jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy
- jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtensionSpec.groovy
Allow actions to be executed when Asciidoctorj detached configuration is created (#511)
Build script authors can registers additional actions to be executed every time the configuration
that holds the asciidcotrj dependencies, is created. This is done via the onConfiguration call.
Actions can be task-specific and can even be completely decoupled from the project actions. If not,
then project actions will be executed before task-specific actions.
> Allow actions to be executed for asciidoctorj detached configuration

- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskSpec.groovy
- Fixes #329
- project.version defaults to 'unspecified' in Gradle
- fix attempt was previously made in https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/337/commits/eb75b4972eb50e9c29e6a97e34c1b75a58bed95c, but that didn't check for `Project.DEFAULT_VERSION` (which is `unspecified`).
> Don't add revnumber attr when project.version is unspecified

- docs/src/docs/asciidoc/parts/asciidoctorj-custom-extensions.adoc
This adds a Kotlin DSL example to the section on Adding Custom Extensions > [As External Library](https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/#_as_external_library) in the Asciidoctor Gradle Plugin Suite guide.
> Added Kotlin DSL example to 'Adding Custom Extensions'

- asciidoctoreditorconfig/src/main/groovy/org/asciidoctor/gradle/editorconfig/AsciidoctorEditorConfigGenerator.groovy
- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- base/src/main/java/org/asciidoctor/gradle/base/slides/SlidesToExportAware.java
- gradle.properties
- gradle/publishing.gradle
- jvm-leanpub/src/main/groovy/org/asciidoctor/gradle/jvm/leanpub/DropboxCopyTask.groovy
- jvm-pdf/src/main/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTask.groovy
- slides-export/src/main/groovy/org/asciidoctor/gradle/slides/export/base/AbstractExportBaseTask.groovy
This PR fixes some validation problems with tasks in the plugin that will cause any build using the plugin to fail with Gradle 7.0. It also enables strict validation during the build, so any new validation problems introduced will make the build fail.
The particular problems fixed by this PR are:
```text
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':asciidoctoreditorconfig:validateTaskProperties'.
> Task property validation failed. See https://docs.gradle.org/5.5.1/userguide/more_about_tasks.html#sec:task_input_output_annotations for more information on how to annotate task properties.
> Warning: Type 'org.asciidoctor.gradle.editorconfig.AsciidoctorEditorConfigGenerator': property 'additionalFileProviders' is missing a normalization …
```
> Fix task property annotation problems

- jvm/src/main/groovy/org/asciidoctor/gradle/internal/JavaExecUtils.groovy
- jvm/src/test/groovy/org/asciidoctor/gradle/internal/JavaExecUtilsSpec.groovy
Avoid hardcoding which variant of Guava Gradle is going to ship with. This allows Gradle to use other variants without breaking the asciidoctor plugin.
> Handle different variants of Guava

- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
The method was doing too many operations, causing very large file sets to
perform poorly.
> Rework AbstractAsciidoctorBaseTask.getSecondarySourceFileTreeFrom

- base/src/main/groovy/org/asciidoctor/gradle/base/Transform.groovy
The `Transform.toSet()` methods return a HashSet instance that has non-deterministic ordering.
These methods are used to construct a number of task inputs and outputs, including:
- `AbstractAsciidoctorBaseTask.getBackendOutputDirectories`
- `AsciidoctorEpubTask.ebookFormats`
- `AbstractAsciidoctorTask.configurations`
It is important that task inputs and outputs are consistent to ensure Gradle can correctly determine if a task is up-to-date.
These are not just theoretical issues, as reported by #591.
When `docExtensions` are added as Closures to `asciidoctorj`, the `AbstractAsciiDoctorTask` adds a number of Gradle/Groovy dependencies to the Classpath used to invoke Asciidoctor. Since `AbstractAsciidoctorTask.configurations` is registered as a task input, this inconsistent classpath …
> Ensure consistent ordering in Sets returned from `Transform.toSet()`

- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorJRevealJSTask.groovy
- jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
This changes adds name declarations in several places where input properties were being declared without property names.  Without property names, inputs declared with the runtime API are assigned names like `$1` which are unhelpful while troubleshooting.
> Add name declarations to unnamed input properties

- .github/actions/setup-jdk/action.yml
- .github/workflows/build.yml
it already includes smart caching of the gradle home files,
so remove manual caching for that.
Extract setup jdk logic into a local workflow snippet.
Update actions/checkout to v2 and use fetch-depth
> Use the official gradle/gradle-build-action

- jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
The main property is going to be replaced by mainClass in the JavaExec class.
Dynamically attempt to continue calling the original property, but upon failure call the new property instead.
Fixes #602 and (somewhat) #611.
> Support removal of main property in Gradle 8.0

- jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskFunctionalSpec.groovy
- jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
Gradle 8.0 will retire the deprecated WorkerExecutor.submit() method. This PR changes the plugin's use of the worker API to use the new methods introduced in Gradle 5.6.
> Support latest worker API for Gradle 8.0 compatibility

- base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
- jvm-pdf/src/main/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTask.groovy
So SkipWhenEmpty keeps working as now with Gradle 8.0. See https://docs.gradle.org/current/userguide/upgrading_version_7.html#empty_directories_file_tree.
> Add `@IgnoreEmptyDirectories` where adequate

- js/src/main/groovy/org/asciidoctor/gradle/js/base/AbstractAsciidoctorJSExtension.groovy
A very small and tiny single char typo fix
> Fix a typo in javadoc

- .github/workflows/build.yml
- .github/workflows/push-documentation.yml
- build.gradle
- docs/build.gradle
- gradle.properties
- renovate.json
- testfixtures/jvm/build.gradle
We can kick these things by enabling @renovate-bot and keep this repo up to date.
> Minor updates

- build.gradle
Otherwise the value of 'org.gradle.jvm.version' is set to the JVM used during build.
> Set Java Toolchain to enforce module JVM to 8

- .github/workflows/push-documentation.yml
Fix https://github.com/asciidoctor/asciidoctor-gradle-plugin/actions/runs/7467258592/job/20320388258
> Fix doc publication job

- .github/workflows/push-documentation.yml
Completing https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/708
From the error in [CI](https://github.com/asciidoctor/asciidoctor-gradle-plugin/actions/runs/7679511253/job/20930480087#step:6:607) we can infer the arguments are interpreted as independent statements.
```
/home/runner/work/_temp/f899399a-9ce7-4712-b5d6-6c9ed60e3894.sh: line 3: -Dorg.ajoberstar.grgit.auth.username=: command not found
```
> Use '\' to chain arguments in doc publication pipeline

- jvm/src/main/groovy/org/asciidoctor/gradle/remote/AsciidoctorJSetup.groovy
- jvm/src/main/groovy/org/asciidoctor/gradle/remote/ExecutorBase.groovy
This PR replaces the usage of the deprecated `convertFile` method used [here](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/jvm/src/main/groovy/org/asciidoctor/gradle/remote/AsciidoctorJavaExec.groovy#L87).
This method is removed in Asciidoctor 3.x as mentioned [here](https://docs.asciidoctor.org/asciidoctorj/latest/guides/api-migration-guide-v25x-to-v30/#removal-of-methods-using-mapstringobject-as-options-input), which makes it impossible to use this plugin with Asciidoctor 3.x
> Do not use deprecated methods removed in Asciidoctor 3.x

- gradle/compatibility-tests.gradle
Gradle 8.8 has a problem: https://github.com/spring-projects/spring-framework/pull/33213, so upgrade to 8.9
> Update compatibility-tests.gradle to 8.9

- jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
Set a propertyName and pathSensitivity to RELATIVE for asciidoc-Task Inputs to fix a cache missmatch when the build happens on a different machine and the absolute path is different.
> Fix: Cache mismatch when absolute Path differ

- js/src/main/groovy/org/asciidoctor/gradle/js/nodejs/AsciidoctorJSExtension.groovy
- js/src/main/groovy/org/asciidoctor/gradle/js/nodejs/core/NodeJSDependencyFactory.groovy
- slides-export/src/main/groovy/org/asciidoctor/gradle/slides/export/decktape/DeckTapeExtension.groovy
SelfResolvingDependency has been deprecated in Gradle 8.x and will be removed in Gradle 9.0
BaseNpmSelfResolvingDependency implements this API, as well as Dependency, and SelfResolvingDependencyInternal.
Implementing Gradle interfaces like Dependency is asking for trouble, as these APIs are subject to change in Gradle major versions. Plus, implementing these APIs often require also implementing internal types.
`BaseNpmSelfResolvingDependency` will be impacted by multiple breaking changes in Gradle 9.0:
- https://docs.gradle.org/current/userguide/upgrading_version_8.html#deprecate_self_resolving_dependency
- https://docs.gradle.org/current/userguide/upgrading_version_8.html#deprecated_content_equals
This commit removes all references to SelfResolvingDependency, and all references to …
> Avoid SelfResolvingDependency
